export class applicationDetails {
    loginid:any|undefined;
    aadhar:any|undefined;
    religion:string|undefined;
    community:string|undefined;
    fatherName:string|undefined;
    motherName:string|undefined;
    annualIncome:any|undefined;
    admissionfee:any|undefined;
    institution:string |undefined;
    presentClass:string | undefined;
    presentClassYear:any| undefined;
    modeofstudy:string | undefined;
    classofdate: any |undefined;
    university:string |undefined;
    previousClass:string |undefined;
    previousClassYear:any|undefined;
    previousPercentage:number|undefined;
    tuitionfee:any|undefined;
    otherfee:any|undefined;
    tenthrollno:any|undefined;
    tenthboardname:any|undefined;
    tenthyear:any|undefined;
    tenthpercentage:any|undefined;
    twelthrollno:any|undefined;
    twelthboardname:any|undefined;
    twelthyear:any|undefined;
    twelthpercentage:any|undefined;
    isdisabled:any|undefined;
    typeofdisability:any|undefined;
    disabilitypercent:any|undefined;
    maritalstatus:any|undefined;
    parentsprofession:any|undefined;
    gender:any|undefined;
    scheme:any|undefined;
    state:string|undefined;
    district:string|undefined;
    taluk:string|undefined;
    houseno:string|undefined;
    streetno:string|undefined;
    pincode:any|undefined;
}
